### model
model_name_or_path: Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: formulaqa_train,formulaqa_train_origin
template: llama3
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/tabaf/llama3.1-8b/lora
logging_steps: 10
save_steps: 500
save_total_limit: 10
load_best_model_at_end: true
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: formulaqa_dev,formulaqa_dev_origin
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
